name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Generate Snake
    runs-on: ubuntu-latest

    steps:
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: BecaIanz

          outputs: |
            dist/github-contribution-grid-snake.gif?color_snake=#9845D9&color_dots=#0D1117,#2A1640,#5B2A86,#7A36B2,#9845D9&color_background=#0D1117

      - name: Publish Snake
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: "Update Snake animation"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

